POST http://localhost:8080/events
Content-Type: application/json

{
    "name": "test event",
    "description": "test event description",
    "location": "A test event location",
    "dateTime": "2025-01-01T14:30:00Z"
}